### ISSUE TITLE
Feature - post comment on form submit

### ISSUE THREAD

**Issue by applicationuser** [aptkingston/budibase-comment-box#11]
Able to Post comment on form submit/save action along with comment box post button.

form action can create workflow related comments and post to comments box

example: on form submit, based on business requirement an email send or other external action performed that can logged in comments box

**Comment by aptkingston** [comment]
Hey @applicationuser. Plugins can't expose custom actions, so there's no way to do this through the plugin. You'd have to manually do this with a normal text area field, then run some JS to manually add it to your comment chain. `atob` and `btoa` aren't exposed in JS bindings though so it's not possible to do this currently (as you pointed out yourself) so it would be a good idea to raise a feature request for that in the main Budibase repo and we'll get them added :)

Going to close this one off though since there's nothing I can do in this plugin to help with that.

I've added your other feature request though in b4a54d8 for 2 new props to control whether you can add or remove comments.
