### ISSUE TITLE
Not able to select a table

### ISSUE THREAD

**Issue by robreuer** [aptkingston/budibase-comment-box#2]
It installed without problems (I used the GitHub-Link for installation).
I can insert it into a form. But then I have no possibility to select a table to bind the plugin. The table-dropdown is just empty.

Is there anything I must consider to use the plugin?

**Comment by magedzamzam** [comment]
I have the same problem, I think the problem is with the data type selected as "table" not "dataProvider"

**Comment by aptkingston** [comment]
It's deliberately set to `table` - it's designed to work with tables only. It needs to be used with either an internal table or a SQL table. It's not possible to use it with external queries. You can put it inside a form if you want, but it's not really a form field.

The comment box automatically fetches comments and saves new comments, without needing any sort of button actions or other configuration, which is why it can only work with tables.

**Comment by robreuer** [comment]
Thanks for the explanation. The concept is clear now.
In my case, I have 3 MySQL tables and 1 internal table. But there is no table selectable. The dropdown is just empty

**Comment by robreuer** [comment]
another comment discusses same issue
